# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-10 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(default='default', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('numberOfRooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_accomodation', models.DateTimeField()),
                ('end_accomodation', models.DateTimeField()),
                ('amountOfPersons', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('apartments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Apartments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wi_fi', models.BooleanField(default=False, max_length=1)),
                ('pool', models.BooleanField(default=False, max_length=1)),
                ('spa', models.BooleanField(default=False, max_length=1)),
                ('allowed_pets', models.BooleanField(default=False, max_length=1)),
                ('conditioner', models.BooleanField(default=False, max_length=1)),
                ('restaraunt', models.BooleanField(default=False, max_length=1)),
                ('bar', models.BooleanField(default=False, max_length=1)),
                ('gym', models.BooleanField(default=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_index', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('imageUrl', models.CharField(default='default', max_length=255)),
                ('description', models.CharField(max_length=500, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Street'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Hotel'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartments',
            name='apartmentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.ApartmentType'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Conditions'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Hotel'),
        ),
        migrations.AddField(
            model_name='apartmentimages',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Apartments'),
        ),
    ]
