# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
