# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190411_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='imageUrl',
            field=models.CharField(max_length=255),
        ),
    ]
