# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190411_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='imageUrl',
        ),
    ]
