# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_apartments_imageurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Street',
        ),
    ]
