# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-20 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20190416_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
        migrations.AddField(
            model_name='apartments',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
