# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20190420_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
    ]
