# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-08 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmenttype',
            name='maxPersons',
            field=models.IntegerField(default=2),
        ),
    ]
